# Generated by Django 2.2.4 on 2020-01-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertoken',
            table='user_token',
        ),
    ]
