# Generated by Django 2.2.4 on 2020-01-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_auto_20200128_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='recognition.EntityType'),
        ),
        migrations.AlterUniqueTogether(
            name='entitytype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='entitytype',
            name='user',
        ),
    ]
