# Generated by Django 2.2.4 on 2020-01-29 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_auto_20200129_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recognition.EntityType'),
        ),
    ]
