# Generated by Django 2.2.4 on 2020-01-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0004_auto_20200129_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
