# Generated by Django 2.2.4 on 2020-03-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0007_course_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
