# Generated by Django 2.2.4 on 2020-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0008_auto_20200310_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.IntegerField(choices=[(1, 'PAZARTESI'), (2, 'SALI'), (3, 'CARSAMBA'), (4, 'PERSEMBE'), (5, 'CUMA')], default=1),
        ),
    ]
