# Generated by Django 2.2.4 on 2020-03-10 14:43

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0009_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
