# Generated by Django 2.2.4 on 2020-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0010_auto_20200310_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=9),
        ),
    ]
