# Generated by Django 2.2.4 on 2020-06-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0012_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
